@startuml

title "Kvaser CANLib Wrapper Library's Class diagram"

package API{

    class KPortControlUI<<boundary>>{
        +Button OpenBtn
        +Button CloseBtn
        +ComboBox ChannelCombo
        -void RegisterPorts()
        -int SelectBitrate()
        +Event PortOpened
        +Event PortClosed
    }

    class KvaserControl<< (S, #AAAA00) Singleton>>{
        -int HandleNo
        +bool IsOpened
        +bool IsMonitoring
        +bool BusOn()
        +bool BusOff()
        +bool StartRecv(IReceiver)
        +bool StopRecv(IReceiver)
        +bool SendMessage(Frame)
        +bool SendAndWait(ICommand)
    }

    entity Frame<<Entity>>{
        +int CANID
        +int IDE
        +int RTR
        +int DLC
        +Byte[] Data
        +long Timestamp
        +bool IsError
        +void Init(int iniVal)
        +Frame Clone()
        +String ToCSV()
    }

    Interface IReceiver<<Service>>{
        bool IsReceiving
        Dictionary<T, String> Buff
        Queue<T> RecvData
        Event OwnDataReceived
        bool StartRecv(IReceiver)
        bool StopRecv(IReceiver)
        bool ReceiveProccess(Frame)
    }

    Interface ICommand<<Entity>>{
        +Frame SendMess
        +Frame RecvMess
        +CommandState State
        +bool Parse(Frame)
        +bool IsSuccessedSend()
        +bool IsTimeout()
    }

    Enum CommandState<<State>>{
        NotSend = 0
        Waiting
        RecvACK
        RecvNACK
        Canceled
        Timeout
    }

    KPortControlUI "1" -l-o "1" KvaserControl

    KvaserControl "1" -l "1..*" Frame
    KvaserControl "1" -u-o "1..*" IReceiver
    KvaserControl "1" -u- "0..*" ICommand

    ICommand - CommandState
    ICommand *-l Frame
}

package InternalModules{
    class PortController<< (M, #FF7700) Module>>{
        -{field} Dictinary<int, PortParameter> Ports
        ~int HandleNo
        ~bool HasPorts()
        ~void ScanPorts()
        ~String[] GetPortsInfo()
        ~List<PortParameter> GetPhysicalPorts()
        ~List<PortParameter> GetVirtualPorts()
        -bool SetBusParam(int bitrate)
        ~bool BusOn(int handleNo)
        ~bool BusOff()
    }

    entity PortParameter{
        +int No
        +String Name
        +int SerialNo
        +bool IsVirtual
    }

    class RecvMonitor<< (M, #FF7700) Module>>{
        -Thread MonitoringThread
        ~int HandleNo
        -Queue Buff
        ~bool IsMonitoring
        -void MonitoringLoop()
        ~bool StartMonitoring()
        ~bool StopMonitoring()
        -bool ReadBus()
        -void ExcuteReceiveProcess(Frame)
        ~void ClearBuff()
    }

    class ReceiverManager<< (M, #FF7700) Module>>{
        ~HashSet<IReceiver> Receivers
        ~bool StartRecv(IReceiver)
        ~bool StopRecv(IReceiver)
        -void ClearReceivers()
    }

    class MessageSender<< (M, #FF7700) Module>>{
        ~int HandleNo
        ~bool CheckFormat(Frame)
        ~bool SendMessage(Frame)
        ~bool SendAndWait(ICommand)
    }

    RecvMonitor -l> ReceiverManager
    MessageSender -> ReceiverManager
    
    PortController *-- PortParameter
}


KPortControlUI ---> PortController

KvaserControl ---> PortController
KvaserControl *---> RecvMonitor
KvaserControl *---> ReceiverManager
KvaserControl *---> MessageSender

IReceiver <-- ReceiverManager
IReceiver <-- RecvMonitor



@enduml